#Create a list and perform the following methods 1) insert() 2) remove() 3) append() 
# len() 5) pop() 6) clear() 

list1 = [1,2,3,4,5]
print(list1)
list1.insert(2,6)
print(list1)
list1.remove(6)
print(list1)
list1.append(7)
print(list1)
print(len(list1))
list1.pop()
print(list1)
list1.clear()
print(list1)